import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProviderComponent from "@/components/ProviderComponents";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SolarCraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderComponent>{children}</ProviderComponent>
      </body>
    </html>
  );
}
